environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "7"
    - nodejs_version: "6"
    - nodejs_version: "4"

platform:
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm config set spin false
  - npm i -g npm@latest
  - npm install

test_script:
  - npm test

matrix:
  fast_finish: true

build: off
